# Generated by Django 6.0.1 on 2026-08-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_created_by_school_division_school_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting for Student'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='accounts.parent')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='accounts.student')),
            ],
            options={
                'db_table': 'parent_student_link',
                'constraints': [models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_link')],
            },
        ),
    ]
