# Generated by Django 6.0.1 on 2026-08-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parentstudentlink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_principal_per_school'),
        ),
    ]
