# Generated by Django 6.0.1 on 2026-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_designation_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_grading_component',
            field=models.CharField(choices=[('written_work', 'Written Works'), ('performance_task', 'Performance Tasks'), ('assessment', 'Quarterly Assessment')], default='written_work', max_length=30),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=1),
        ),
    ]
