# Generated by Django 6.0.1 on 2026-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpreference_default_grading_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('module', 'New Module'), ('deadline', 'Deadline Reminder'), ('class_announcement', 'Class Announcement'), ('school_announcement', 'School Announcement'), ('submission', 'New Submission'), ('join_request', 'Join Request'), ('grade_released', 'Grade Released'), ('attendance', 'Attendance Alert'), ('feedback', 'Teacher Feedback'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
