# Generated by Django 6.0.1 on 2026-08-19 15:22

import classroom.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_school_created_by_school_division_school_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(default=classroom.models.generate_class_code, editable=False, max_length=10, unique=True)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quarter', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('3', 'Third Quarter'), ('4', 'Fourth Quarter')], default='1', max_length=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_classes', to='accounts.teacher')),
            ],
            options={
                'db_table': 'class',
                'ordering': ['subject', 'section'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_student', 'Waiting for Student'), ('pending_teacher', 'Waiting for Teacher'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='accounts.student')),
                ('classroom', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom')),
            ],
            options={
                'db_table': 'class_enrollment',
                'constraints': [models.UniqueConstraint(fields=('classroom', 'student'), name='unique_classroom_student')],
            },
        ),
    ]
