# Generated by Django 6.0.1 on 2026-09-07 17:09

import classroom.module_storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_principal_unique_principal_per_school'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('pdf', models.FileField(storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.module_pdf_path)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=1)),
                ('answer_mode', models.CharField(choices=[('structured', 'Numbered answer sheet'), ('written', 'Written response'), ('file', 'Answer file')], default='structured', max_length=20)),
                ('max_score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('allow_late', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='classroom.classroom')),
            ],
            options={
                'db_table': 'learning_module',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=250)),
                ('answer_type', models.CharField(choices=[('short', 'Short answer'), ('choice', 'Multiple choice: A-D'), ('long', 'Long answer')], default='short', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='classroom.module')),
            ],
            options={
                'db_table': 'module_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('written_answer', models.TextField(blank=True)),
                ('answer_file', models.FileField(blank=True, storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.submission_file_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_submissions', to='accounts.student')),
            ],
            options={
                'db_table': 'module_submission',
            },
        ),
        migrations.CreateModel(
            name='ModuleAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.moduleitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.modulesubmission')),
            ],
            options={
                'db_table': 'module_answer',
            },
        ),
        migrations.AddConstraint(
            model_name='moduleitem',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='unique_module_item_position'),
        ),
        migrations.AddConstraint(
            model_name='modulesubmission',
            constraint=models.UniqueConstraint(fields=('module', 'student'), name='unique_module_student_submission'),
        ),
        migrations.AddConstraint(
            model_name='moduleanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'item'), name='unique_submission_item_answer'),
        ),
    ]
