# Generated by Django 6.0.1 on 2026-09-16 16:33

import classroom.module_storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_module_moduleitem_modulesubmission_moduleanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hidden_pages',
            field=models.CharField(blank=True, help_text='Teacher-only PDF pages, for example: 18, 20-22', max_length=250),
        ),
        migrations.AddField(
            model_name='module',
            name='student_pdf',
            field=models.FileField(blank=True, storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.student_module_pdf_path),
        ),
        migrations.AddField(
            model_name='module',
            name='week',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='modulesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for revision')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ModuleAnswerSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_method', models.CharField(choices=[('structured', 'Structured answer sheet'), ('written', 'Written workspace'), ('file', 'File or photo submission'), ('none', 'No answer required')], default='structured', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('max_score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('include_in_grade', models.BooleanField(default=True)),
                ('grading_component', models.CharField(choices=[('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('assessment', 'Assessment'), ('not_graded', 'Not graded')], default='written_work', max_length=30)),
                ('max_files', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sections', to='classroom.module')),
            ],
            options={
                'db_table': 'module_answer_section',
                'ordering': ['position', 'section_id'],
            },
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True or false'), ('identification', 'Identification'), ('number', 'Number'), ('short', 'Short answer'), ('long', 'Essay / long answer')], default='short', max_length=25)),
                ('choices_text', models.TextField(blank=True, help_text='Enter one choice per line.')),
                ('correct_answer', models.TextField(blank=True, help_text='Leave blank when the Teacher will check the answer.')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('required', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.moduleanswersection')),
            ],
            options={
                'db_table': 'module_section_question',
                'ordering': ['position', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='SectionResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('written_answer', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('auto_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='classroom.moduleanswersection')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_responses', to='classroom.modulesubmission')),
            ],
            options={
                'db_table': 'module_section_response',
            },
        ),
        migrations.CreateModel(
            name='SectionAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.sectionquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.sectionresponse')),
            ],
            options={
                'db_table': 'module_section_answer',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.submission_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classroom.sectionresponse')),
            ],
            options={
                'db_table': 'module_submission_attachment',
            },
        ),
        migrations.AddConstraint(
            model_name='sectionresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'section'), name='unique_submission_section_response'),
        ),
        migrations.AddConstraint(
            model_name='sectionanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_response_question_answer'),
        ),
    ]
