# Generated by Django 6.0.1 on 2026-09-16 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_principal_unique_principal_per_school'),
        ('classroom', '0004_make_module_sections_written_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_work_weight', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_task_weight', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessment_weight', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_settings', to='classroom.classroom')),
            ],
            options={
                'db_table': 'gradebook_settings',
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('component', models.CharField(choices=[('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('assessment', 'Quarterly Assessment')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('highest_possible_score', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='classroom.classroom')),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_item', to='classroom.module')),
            ],
            options={
                'db_table': 'grade_item',
                'ordering': ['term', 'component', 'position', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='GradeScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='classroom.gradeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scores', to='accounts.student')),
            ],
            options={
                'db_table': 'grade_score',
            },
        ),
        migrations.AddConstraint(
            model_name='gradeitem',
            constraint=models.UniqueConstraint(fields=('classroom', 'term', 'component', 'position'), name='unique_grade_item_position'),
        ),
        migrations.AddConstraint(
            model_name='gradescore',
            constraint=models.UniqueConstraint(fields=('item', 'student'), name='unique_grade_item_student_score'),
        ),
    ]
