# Generated by Django 6.0.1 on 2026-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_gradebooksettings_gradeitem_gradescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebooksettings',
            name='term_1_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradebooksettings',
            name='term_2_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradebooksettings',
            name='term_3_released',
            field=models.BooleanField(default=False),
        ),
    ]
