# Generated by Django 6.0.1 on 2026-09-16 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_principal_unique_principal_per_school'),
        ('classroom', '0006_gradebooksettings_term_1_released_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('attendance_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('class_day', 'Class day'), ('holiday', 'Holiday'), ('no_class', 'No class')], default='class_day', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Example: Independence Day, typhoon suspension, or school activity.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='classroom.classroom')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendance_days', to='accounts.teacher')),
            ],
            options={
                'db_table': 'attendance_day',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='classroom.attendanceday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.student')),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.AddConstraint(
            model_name='attendanceday',
            constraint=models.UniqueConstraint(fields=('classroom', 'date'), name='unique_classroom_attendance_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('attendance_day', 'student'), name='unique_attendance_day_student'),
        ),
    ]
