# Generated by Django 6.0.1 on 2026-09-18 15:05

import classroom.module_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesubmission',
            name='answered_pdf',
            field=models.FileField(blank=True, storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.submission_file_path),
        ),
        migrations.AddField(
            model_name='modulesubmission',
            name='pdf_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
