# Generated by Django 6.0.1 on 2026-09-18 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_modulesubmission_answered_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='max_score',
            field=models.PositiveIntegerField(default=0, help_text='Set this after reviewing the uploaded Module PDF. A value of 0 means the score has not been set yet.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
