# Generated by Django 6.0.1 on 2026-09-21 16:34

import classroom.module_storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_module_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesubmission',
            name='annotation_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modulesubmission',
            name='current_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modulesubmission',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionExtraPage',
            fields=[
                ('extra_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('essay', 'Written Answer'), ('drawing', 'Blank Drawing Page'), ('upload', 'Uploaded Output')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('related_pdf_page', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveIntegerField(default=1)),
                ('essay_text', models.TextField(blank=True)),
                ('drawing_data', models.JSONField(blank=True, default=list)),
                ('uploaded_file', models.FileField(blank=True, storage=classroom.module_storage.learning_storage, upload_to=classroom.module_storage.submission_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pages', to='classroom.modulesubmission')),
            ],
            options={
                'db_table': 'submission_extra_page',
                'ordering': ['position', 'extra_page_id'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'position'), name='unique_submission_extra_page_position')],
            },
        ),
    ]
