# Generated by Django 6.0.1 on 2026-10-03 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpreference_default_grading_component_and_more'),
        ('classroom', '0011_modulesubmission_annotation_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('school_year', models.CharField(help_text='Example: 2026-2027', max_length=20)),
                ('level', models.CharField(choices=[('district', 'District Official Event'), ('school', 'School Event'), ('classroom', 'Class Event')], max_length=20)),
                ('event_type', models.CharField(choices=[('academic', 'Academic Schedule'), ('holiday', 'Holiday'), ('no_class', 'No Classes'), ('grading', 'Grading Schedule'), ('activity', 'Activity'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('other', 'Other')], default='activity', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('applies_to_all_schools', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='Example: DepEd Order No. 009, s. 2026', max_length=200)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='calendar_sources/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.school')),
                ('target_schools', models.ManyToManyField(blank=True, related_name='district_calendar_events', to='accounts.school')),
            ],
            options={
                'db_table': 'calendar_event',
                'ordering': ['start_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='Example: 2026-2027', max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_academic_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academic_term',
                'ordering': ['school_year', 'term'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'term'), name='unique_school_year_term')],
            },
        ),
    ]
