# Generated by Django 6.0.1 on 2026-10-04 17:25

import classroom.module_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_notification_type'),
        ('classroom', '0012_calendarevent_academicterm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('module', 'Module'), ('activity', 'Activity')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('grade_component', models.CharField(choices=[('not_graded', 'Not graded'), ('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('assessment', 'Assessment')], default='not_graded', max_length=30)),
                ('term', models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, storage=classroom.module_storage.learning_storage, upload_to='class_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_post', to='classroom.announcement')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_posts', to='classroom.classroom')),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_post', to='classroom.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_posts', to='accounts.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('question', 'Question'), ('important', 'Important')], default='normal', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.classpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='classroom_c_post_id_358c76_idx')],
            },
        ),
    ]
