# Generated by Django 6.0.1 on 2026-10-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_backfill_class_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpost',
            name='post_type',
            field=models.CharField(choices=[('post', 'Class Post'), ('announcement', 'Announcement'), ('module', 'Module'), ('activity', 'Activity')], max_length=20),
        ),
    ]
